# cloudbuild.yaml
# cloudbuild.ym
steps:
  # Step 1: Pull the latest backend image to use as cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/$PROJECT_ID/paperrank-backend:latest || exit 0'

  # Step 2: Build the backend image, using the pulled image as cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/paperrank-backend:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/paperrank-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'

  # Step 3: Pull the latest frontend image to use as cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/$PROJECT_ID/paperrank-frontend:latest || exit 0'

  # Step 4: Build the frontend image, using the pulled image as cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/paperrank-frontend:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/paperrank-frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/paperrank-backend:latest'
  - 'gcr.io/$PROJECT_ID/paperrank-frontend:latest'
