
# Use a modern syntax without the version attribute
services:
  # The 'frontend' service builds and runs the Streamlit app
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8501:8501" # Correct port mapping for Streamlilt
    env_file:
      - ./container.env
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - database # Frontend might also need to access the database directly
    # Volumes are useful for live-reloading during development
    volumes:
      - ./frontend:/app
      - ./db:/app/db
      
  # The 'backend' service builds and runs the FastAPI/Uvicorn server
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000" # Correct port mapping for Uvicorn
    # Use env_file to inject secrets and config
    env_file:
      - ./container.env
    depends_on:
      - database # Backend must wait for the database to be ready
    # Volumes for live-reloading during development
    volumes:
      - ./backend:/code
      - ./db:/code/db
      
  # The 'database' service uses a pre-built MongoDB image
  database:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - research:/data/db

# Named volume for persistent database storage
volumes:
  research: